host_group: Applications
hosts_to_add:
  - { hostname: "application-a", ip: "192.168.56.21" }
  - { hostname: "application-b", ip: "192.168.56.22" }
  - { hostname: "application-c", ip: "192.168.56.23" }

services_to_add:
  - { service: "https", port: 443}