---
- name: Zabbix Hosts
  hosts: zabbix_server
  gather_facts: no
  vars_files:
    - ../vars/all.yml

  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: "{{ zabbix_api_port }}"
    ansible_httpapi_use_ssl: "{{ zabbix_api_use_ssl }}"
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: "zabbix"

    category: "{{ category | default('servers') }}"
    desired_state: "{{ state | default('present') }}"
    action_label: "{{ 'Create or Update' if desired_state == 'present' else 'Delete' }}"

  tasks:
    - name: Load {{ category }} targets
      ansible.builtin.include_vars:
        file: "../vars/{{ category }}.yml"

    - name: Set credentials to access Zabbix Server API
      ansible.builtin.set_fact:
        ansible_user: "{{ zabbix_api_user }}"
        ansible_httpapi_pass: "{{ zabbix_api_password }}"

    - name: "{{ action_label }} {{ category }} Hosts"
      loop: "{{ hosts_to_add }}"
      loop_control:
        label: "{{ item.hostname }}"
      community.zabbix.zabbix_host:
        state: "{{ desired_state }}"
        host_name: "{{ item.hostname }}"
        host_groups:
          - "{{ host_group }}"
        link_templates:
          - ICMP Ping
          - HTTP or HTTPS Check
        status: enabled
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ item.ip }}"
            dns: ""
            port: "10050"
        tags:
          - tag: "host"
            value: "{{ item.hostname }}"